language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

sudo: false

env:
  - TEST=PHP_CodeSniffer
  - TEST=PHPUnit

install:
  - composer install

script: ./scripts/travis-ci/run-test.sh ${TEST}
